name: Actions reliability checks line tool workflow

on: [push]

jobs:
  action:
    runs-on: "macos-latest"

    steps:
     - uses: actions/checkout@v1
     - name: Install scorecard
       run: brew install scorecard
     - name: Run checks
       uses: ./.github/actions/checks
       with:
        token: ${{secrets.OSSF_PAT}}
        checkName: Vulnerabilities,Dangerous-Workflow,Binary-Artifacts,Branch-Protection,Code-Review,Dependency-Update-Tool,Pinned-Dependencies,SAST,Security-Policy
